Algoritmo "Exercicio 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson vulgo Professor Obama
// Descrição   : Mostra o antecessor do numero digitado
// Autor(a)    : Erik Caue
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
   numero01, numero02:inteiro

Inicio
   escreval("Escreva um valor")
   leia(numero01)
   numero02 <- numero01 -1
   escreval("O seu antecessor é:",numero02)

Fimalgoritmo