Algoritmo "Exercicio 9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson vulgo Professor Obama
// Descrição   : Efetua e mostra a area de um circulo
// Autor(a)    : Erik Caue
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
   raio, area:real

Inicio

   escreval("Digite o raio de um circulo:")
   leia(raio)
   area <- (raio^2)*pi
   escreval("A área do circulo é:",area)
Fimalgoritmo